spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ecomm
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  boot:
    admin:
      client:
        url: http://localhost:2222/
  mail:
    host: smtp.gmail.com
    password: ${MAIL_PASSWORD}
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: ${MAIL_USERNAME}
  main:
    allow-circular-references: true
server:
  port: 8088
