spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ecomm
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  boot:
    admin:
      client:
        url: http://localhost:2222/
  mail:
    host: smtp.gmail.com
    password: ieac zszr jvdi wjlu
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: krishnachandanada2002@gmail.com

server:
  port: 8089
