spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/ecomm
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  boot:
    admin:
      client:
        url: http://localhost:2222/
  data:
    rest:
      base-path: /ecomm
razorpay:
  key:
    id: rzp_test_mOD8IRgqoi1FwD
  secret:
    key: TsAhh2r0aZDeATKQ9HJENBL7
server:
  port: 8081
